handlebars src/components/ui/button/button.hbs -f dist/button.precompiled.js &&
handlebars src/partial/button/btn-link.hbs -f dist/btn-link.precompiled.js &&
handlebars src/partial/button/button.hbs -f dist/button.precompiled.js &&
handlebars src/partial/netflix-logo/netflix-logo.hbs -f dist/netflix-logo.precompiled.js &&
handlebars src/partial/header/partial-header.hbs -f dist/partial-header.precompiled.js &&
handlebars src/partial/avatar/avatar.hbs -f dist/avatar.precompiled.js &&
handlebars src/partial/footer/partial-footer.hbs -f dist/partial-footer.precompiled.js &&
handlebars src/pages/main/components/main-background.hbs -f dist/main-background.precompiled.js &&
handlebars src/partial/input-control/input-control.hbs -f dist/input-control.precompiled.js &&
handlebars src/pages/main/components/main-form.hbs -f dist/main-form.precompiled.js &&
handlebars src/pages/main/components/main-banner.hbs  -f dist/main-banner.precompiled.js &&
handlebars src/pages/main/components/main-content.hbs -f dist/main-content.precompiled.js &&
handlebars src/pages/404/404.hbs -f dist/404.precompiled.js &&
handlebars src/pages/login/login-page.hbs -f dist/login-page.precompiled.js &&
handlebars src/pages/login/components/login-form.hbs -f dist/login-form.precompiled.js &&
handlebars src/pages/login/components/login-background.hbs -f dist/login-background.precompiled.js &&

handlebars src/pages/feed/components/footer/footer-feed.hbs -f dist/footer-feed.precompiled.js &&
handlebars src/pages/feed/components/header/header-feed.hbs -f dist/header-feed.precompiled.js &&
handlebars src/pages/feed/components/content/feed-content-main.hbs -f dist/feed-content-main.precompiled.js &&
handlebars src/pages/feed/components/content/genre/genre.hbs -f dist/genre.precompiled.js &&
handlebars src/pages/register/components/AlreadyCreatedPasswordContent/AlreadyCreatedPasswordContent.hbs -f dist/AlreadyCreatedPasswordContent.precompiled.js &&
handlebars src/pages/register/components/CreatePasswordContent/CreatePasswordContent.hbs -f dist/CreatePasswordContent.precompiled.js &&
handlebars src/pages/register/components/EmailPreferenceContainer/EmailPreferenceContainer.hbs -f dist/EmailPreferenceContainer.precompiled.js &&
handlebars src/pages/register/components/FinishAccContent/FinishAccContent.hbs -f dist/FinishAccContent.precompiled.js &&
handlebars src/pages/register/components/FormInput/FormInput.hbs -f dist/FormInput.precompiled.js &&
handlebars src/pages/register/components/FormList/FormList.hbs -f dist/FormList.precompiled.js &&
handlebars src/pages/register/components/Header/Header.hbs -f dist/Header.precompiled.js &&
handlebars src/pages/register/components/LinkForgotPassword/LinkForgotPassword.hbs -f dist/LinkForgotPassword.precompiled.js &&
handlebars src/pages/register/components/NetflixLogo/NetflixLogo.hbs -f dist/NetflixLogo.precompiled.js &&
handlebars src/pages/register/components/RegFooter/RegFooter.hbs -f dist/RegFooter.precompiled.js &&
handlebars src/pages/register/components/RegisterContextBody/RegisterContextBody.hbs -f dist/RegisterContextBody.precompiled.js &&
handlebars src/pages/register/components/RegisterStepHeader/RegisterStepHeader.hbs -f dist/RegisterStepHeader.precompiled.js &&
handlebars src/pages/register/components/SignInLink/SignInLink.hbs -f dist/SignInLink.precompiled.js &&
handlebars src/pages/register/components/SubmitRegisterButton/SubmitRegisterButton.hbs -f dist/SubmitRegisterButton.precompiled.js &&
handlebars src/pages/main/main-page.hbs -f dist/main-page.precompiled.js