handlebars src/partial/button/btn-link.hbs -f dist/btn-link.js &&
handlebars src/partial/button/button.hbs -f dist/button.js &&
handlebars src/partial/netflix-logo/netflix-logo.hbs -f dist/netflix-logo.js &&
handlebars src/partial/header/partial-header.hbs -f dist/partial-header.js &&
handlebars src/partial/avatar/avatar.hbs -f dist/avatar.js &&
handlebars src/partial/footer/partial-footer.hbs -f dist/partial-footer.js &&
handlebars src/pages/main/components/main-background.hbs -f dist/main-background.js &&
handlebars src/partial/input-control/input-control.hbs -f dist/input-control.js &&
handlebars src/pages/main/components/main-form.hbs -f dist/main-form.js &&
handlebars src/pages/main/components/main-banner.hbs  -f dist/main-banner.js &&
handlebars src/pages/main/components/main-content.hbs -f dist/main-content.js &&
handlebars src/pages/404/404.hbs -f dist/404.js &&
handlebars src/pages/login/login-page.hbs -f dist/login-page.js &&
handlebars src/pages/login/components/login-form.hbs -f dist/login-form.js &&
handlebars src/pages/login/components/login-background.hbs -f dist/login-background.js &&
handlebars src/pages/register/components/register-form.hbs -f dist/register-form.js &&
handlebars src/pages/register/main-register.hbs -f dist/main-register.js &&
handlebars src/pages/feed/feed-page.hbs -f dist/feed-page.js &&
handlebars src/partial/button/btn-action.hbs -f dist/btn-action.js &&
handlebars src/pages/content/content.hbs -f dist/content.js &&
handlebars src/pages/profile/components/profile-form.hbs -f dist/profile-form.js &&
handlebars src/pages/profile/profile-page.hbs -f dist/profile-page.js &&
handlebars src/pages/content/components/player.hbs -f dist/player.js &&
handlebars src/pages/feed/components/feed-preview.hbs -f dist/feed-preview.js &&
handlebars src/pages/register/start-register.hbs -f dist/start-register.js &&
handlebars src/pages/register/components/start-register-form.hbs -f dist/start-register-form.js &&
handlebars src/pages/main/main-page.hbs -f dist/main-page.js &&
handlebars src/components/notify/notify.hbs -f dist/notify.js &&
handlebars src/pages/feed/components/feed-collection.hbs -f dist/feed-collection.js &&

handlebars src/pages/cast/components/video-item.hbs -f dist/video-item.js &&
handlebars src/pages/cast/cast.hbs -f dist/cast.js
