handlebars src/pages/login/components/footer/footer.hbs -f src/pages/login/components/footer/footer.precompiled.js && 
handlebars src/pages/login/components/header/header.hbs -f src/pages/login/components/header/header.precompiled.js && 
handlebars src/pages/login/components/body/body.hbs -f src/pages/login/components/body/body.precompiled.js &&
handlebars src/pages/feed/components/footer/footer-feed.hbs -f src/pages/feed/components/footer/footer-feed.precompiled.js &&
handlebars src/pages/feed/components/header/header-feed.hbs -f src/pages/feed/components/header/header-feed.precompiled.js &&
handlebars src/pages/feed/components/content/feed-content-main.hbs -f src/pages/feed/components/content/feed-content-main.precompiled.js &&
handlebars src/pages/feed/components/content/genre/genre.hbs -f src/pages/feed/components/content/genre/genre.precompiled.js &&
handlebars src/pages/register/components/AlreadyCreatedPasswordContent/AlreadyCreatedPasswordContent.hbs -f src/pages/register/components/AlreadyCreatedPasswordContent/AlreadyCreatedPasswordContent.precompiled.js &&
handlebars src/pages/register/components/CreatePasswordContent/CreatePasswordContent.hbs -f src/pages/register/components/CreatePasswordContent/CreatePasswordContent.precompiled.js &&
handlebars src/pages/register/components/EmailPreferenceContainer/EmailPreferenceContainer.hbs -f src/pages/register/components/EmailPreferenceContainer/EmailPreferenceContainer.precompiled.js &&
handlebars src/pages/register/components/FinishAccContent/FinishAccContent.hbs -f src/pages/register/components/FinishAccContent/FinishAccContent.precompiled.js &&
handlebars src/pages/register/components/FormInput/FormInput.hbs -f src/pages/register/components/FormInput/FormInput.precompiled.js &&
handlebars src/pages/register/components/FormList/FormList.hbs -f src/pages/register/components/FormList/FormList.precompiled.js &&
handlebars src/pages/register/components/Header/Header.hbs -f src/pages/register/components/Header/Header.precompiled.js &&
handlebars src/pages/register/components/LinkForgotPassword/LinkForgotPassword.hbs -f src/pages/register/components/LinkForgotPassword/LinkForgotPassword.precompiled.js &&
handlebars src/pages/register/components/NetflixLogo/NetflixLogo.hbs -f src/pages/register/components/NetflixLogo/NetflixLogo.precompiled.js &&
handlebars src/pages/register/components/RegFooter/RegFooter.hbs -f src/pages/register/components/RegFooter/RegFooter.precompiled.js &&
handlebars src/pages/register/components/RegisterContextBody/RegisterContextBody.hbs -f src/pages/register/components/RegisterContextBody/RegisterContextBody.precompiled.js &&
handlebars src/pages/register/components/RegisterStepHeader/RegisterStepHeader.hbs -f src/pages/register/components/RegisterStepHeader/RegisterStepHeader.precompiled.js &&
handlebars src/pages/register/components/SignInLink/SignInLink.hbs -f src/pages/register/components/SignInLink/SignInLink.precompiled.js &&
handlebars src/pages/register/components/SubmitRegisterButton/SubmitRegisterButton.hbs -f src/pages/register/components/SubmitRegisterButton/SubmitRegisterButton.precompiled.js &&
handlebars src/pages/main/main-page.hbs -f src/pages/main/main-page.precompiled.js